# Generated by Django 2.2 on 2020-01-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orlHost', models.TextField()),
                ('orlPort', models.TextField()),
                ('orlServiceName', models.TextField()),
                ('orlSchemaName', models.TextField()),
                ('orlUserName', models.TextField()),
                ('orlPassword', models.TextField()),
                ('mysqlHost', models.TextField()),
                ('mysqlPort', models.TextField()),
                ('mysqlDatabaseName', models.TextField()),
                ('mysqlUserName', models.TextField()),
                ('mysqlPassword', models.TextField()),
            ],
        ),
    ]
