# Generated by Django 2.2 on 2020-01-12 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_dbitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DBItems',
            new_name='DBItem',
        ),
    ]
